
package service.endpoint;

import types.ObjectFactory;
import types.ListOfTable;
import types.Table;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TableService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TableService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumber", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetNumber")
    @ResponseWrapper(localName = "getNumberResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetNumberResponse")
    @Action(input = "http://endpoint.service/TableService/getNumberRequest", output = "http://endpoint.service/TableService/getNumberResponse")
    public int getNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns service.endpoint.ListOfTable
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTovar", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllTovar")
    @ResponseWrapper(localName = "getAllTovarResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllTovarResponse")
    @Action(input = "http://endpoint.service/TableService/getAllTovarRequest", output = "http://endpoint.service/TableService/getAllTovarResponse")
    public ListOfTable getAllTovar();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.endpoint.ListOfTable
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delDogovor", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DelDogovor")
    @ResponseWrapper(localName = "delDogovorResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DelDogovorResponse")
    @Action(input = "http://endpoint.service/TableService/delDogovorRequest", output = "http://endpoint.service/TableService/delDogovorResponse")
    public ListOfTable delDogovor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.endpoint.ListOfTable
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewDogovor", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewDogovor")
    @ResponseWrapper(localName = "setNewDogovorResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewDogovorResponse")
    @Action(input = "http://endpoint.service/TableService/setNewDogovorRequest", output = "http://endpoint.service/TableService/setNewDogovorResponse")
    public ListOfTable setNewDogovor(
        @WebParam(name = "arg0", targetNamespace = "")
        Table arg0);

}
