
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TableServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/wserver/TableService?wsdl")
public class TableServiceService
    extends Service
{

    private final static URL TABLESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TABLESERVICESERVICE_EXCEPTION;
    private final static QName TABLESERVICESERVICE_QNAME = new QName("http://endpoint.service/", "TableServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wserver/TableService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TABLESERVICESERVICE_WSDL_LOCATION = url;
        TABLESERVICESERVICE_EXCEPTION = e;
    }

    public TableServiceService() {
        super(__getWsdlLocation(), TABLESERVICESERVICE_QNAME);
    }

    public TableServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TABLESERVICESERVICE_QNAME, features);
    }

    public TableServiceService(URL wsdlLocation) {
        super(wsdlLocation, TABLESERVICESERVICE_QNAME);
    }

    public TableServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TABLESERVICESERVICE_QNAME, features);
    }

    public TableServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TableServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TableService
     */
    @WebEndpoint(name = "TableServicePort")
    public TableService getTableServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "TableServicePort"), TableService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TableService
     */
    @WebEndpoint(name = "TableServicePort")
    public TableService getTableServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "TableServicePort"), TableService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TABLESERVICESERVICE_EXCEPTION!= null) {
            throw TABLESERVICESERVICE_EXCEPTION;
        }
        return TABLESERVICESERVICE_WSDL_LOCATION;
    }

}
